services:
  test_db:
    image: postgis/postgis:16-3.4-alpine
    container_name: jamsessions_test_db
    volumes: # create schema and roles on startup
      - ./internal/db/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql
      - ./internal/db/scripts/add-roles.sh:/docker-entrypoint-initdb.d/002_roles.sh
    ports:
      - "127.0.0.1:$TEST_DB_PORT:5432" # we expose it to localhost only
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      READ_ONLY_PASSWORD: $READ_ONLY_PASSWORD
      READ_WRITE_PASSWORD: $READ_WRITE_PASSWORD