#################
#       DEV     #
#################

ARG GO_VERSION

FROM golang:$GO_VERSION AS development

# Add a work directory
WORKDIR /app
# Cache and install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy app files
COPY . .

# install air for hot reload
RUN go install github.com/air-verse/air@latest
# Expose port
EXPOSE 80

ENV GOCACHE /app/tmp/.cache

# Start app
CMD air --build.cmd "go build -o ./bin/server ./cmd/server" --build.bin "./bin/server"