#!/bin/env bash

psql -v ON_ERROR_STOP=1 -U postgres -d $POSTGRES_DB <<-END
ALTER DATABASE ${POSTGRES_DB} SET timezone TO 'UTC';

-- Making sure roles can't do anything on the database without explicit grant
REVOKE ALL ON SCHEMA ${POSTGRES_DB} FROM public;
REVOKE ALL ON DATABASE ${POSTGRES_DB} FROM public;

-- Create read-only user
CREATE ROLE read_only LOGIN PASSWORD '${READ_ONLY_PASSWORD}';

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO read_only;
GRANT USAGE ON SCHEMA ${POSTGRES_DB} TO read_only;
GRANT SELECT ON ALL TABLES IN SCHEMA ${POSTGRES_DB} TO read_only;

-- read-write user
CREATE ROLE read_write LOGIN PASSWORD '${READ_WRITE_PASSWORD}';

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO read_write;
GRANT USAGE ON SCHEMA ${POSTGRES_DB} TO read_write;
GRANT SELECT ON ALL TABLES IN SCHEMA ${POSTGRES_DB} TO read_write;
GRANT INSERT ON ALL TABLES IN SCHEMA ${POSTGRES_DB} TO read_write;
GRANT UPDATE ON ALL TABLES IN SCHEMA ${POSTGRES_DB} TO read_write;
GRANT DELETE ON ALL TABLES IN SCHEMA ${POSTGRES_DB} TO read_write;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA ${POSTGRES_DB} TO read_write;
END