services: 

  dev_db:
    image: postgis/postgis:16-3.4-alpine
    container_name: jamsessions_dev_db
    volumes: # create schema and roles on startup
      - ./backend/internal/db/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql
      - ./backend/internal/db/scripts/add-roles.sh:/docker-entrypoint-initdb.d/002_roles.sh
      - ./backend/internal/db/scripts/add-test-data.sql:/docker-entrypoint-initdb.d/003_data.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      READ_ONLY_PASSWORD: $READ_ONLY_PASSWORD
      READ_WRITE_PASSWORD: $READ_WRITE_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U read_write -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  dev_api:
    build:
      context: backend
      target: development
      args:
        GO_VERSION: 1.23
        USER: $DEV_USER
        UID: $DEV_UID
    image: jamsessions_dev_api
    container_name: jamsessions_dev_api
    volumes:
      - "./backend:/app"
    environment:
      DB_URL: "host=dev_db port=5432 user=read_write password=${READ_WRITE_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable"
      MIGRATIONS_DIRECTORY: /app/migrations
      MIGRATIONS_SUGGESTIONS: /app/migrations/suggestions
      SERVER_ADDRESS: 0.0.0.0:80
    depends_on:
      - dev_db
    ports:
      - "127.0.0.1:${DEV_API_PORT}:80"
    healthcheck:
      test: ["CMD", "/app/bin/healthcheck", "http://localhost:80"]
      interval: 1s 
      timeout: 1s
      retries: 3

  dev_frontend:
    build:
      context: frontend
      target: development
    image: jamsessions_dev_frontend
    container_name: jamsessions_dev_frontend
    environment:
      API_ADDRESS: http://localhost:$DEV_API_PORT
      TILES_ADDRESS: http://localhost:$DEV_TILES_PORT
    volumes:
      - "./frontend:/workspace"
      - "node_modules_jamsessions:/workspace/node_modules"
    command: ["--", "--host", "0.0.0.0", "--port", "5173"]
    ports:
      - "127.0.0.1:$DEV_FRONTEND_PORT:5173"
    restart: unless-stopped
    depends_on:
      - dev_api

  # dev_tile_server:
  #   image: caddy:2.8.4-alpine
  #   container_name: jamsessions_dev_tiles
  #   environment:
  #     FRONTEND_URL: http://localhost:$DEV_FRONTEND_PORT
  #   volumes: 
  #     - ./tiles/Caddyfile:/etc/caddy/Caddyfile
  #     - ./tiles/london.pmtiles:/files/london.pmtiles
  #   restart: unless-stopped
  #   ports:
  #     - "127.0.0.1:${DEV_TILES_PORT}:80"

volumes:
  node_modules_jamsessions: