// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbutils

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LondonJamSessionsComment struct {
	CommentID int32              `json:"comment_id"`
	Session   int32              `json:"session"`
	Author    string             `json:"author"`
	Content   string             `json:"content"`
	DtPosted  pgtype.Timestamptz `json:"dt_posted"`
}

type LondonJamSessionsJamsession struct {
	SessionID       int32              `json:"session_id"`
	SessionName     string             `json:"session_name"`
	Venue           int32              `json:"venue"`
	Genres          []string           `json:"genres"`
	StartTimeUtc    pgtype.Timestamptz `json:"start_time_utc"`
	Interval        string             `json:"interval"`
	DurationMinutes int16              `json:"duration_minutes"`
	Description     string             `json:"description"`
	SessionWebsite  *string            `json:"session_website"`
	DtUpdatedUtc    pgtype.Timestamptz `json:"dt_updated_utc"`
}

type LondonJamSessionsRating struct {
	RatingID int32              `json:"rating_id"`
	Session  int32              `json:"session"`
	Comment  *int32             `json:"comment"`
	Rating   *int16             `json:"rating"`
	DtPosted pgtype.Timestamptz `json:"dt_posted"`
}

type LondonJamSessionsVenue struct {
	VenueID           int32              `json:"venue_id"`
	VenueName         string             `json:"venue_name"`
	AddressFirstLine  string             `json:"address_first_line"`
	AddressSecondLine *string            `json:"address_second_line"`
	City              string             `json:"city"`
	Postcode          string             `json:"postcode"`
	Geom              interface{}        `json:"geom"`
	VenueWebsite      *string            `json:"venue_website"`
	Backline          []string           `json:"backline"`
	VenueComments     []string           `json:"venue_comments"`
	VenueDtUpdatedUtc pgtype.Timestamptz `json:"venue_dt_updated_utc"`
}
