name: Run backend test suite

on:
  pull_request:
    paths:
      - "backend/*"

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION }}
      - name: Install dependencies
        working-directory: ./backend
        run: go get .
      - name: Run test suite
        working-directory: ./backend
        run: make test-ci > test_results.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: backend_test_results
          path: backend/test_results.json
