name: Run backend test suite

on:
  pull_request:
    paths:
      - "backend/*"

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './backend'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION }}
          cache-dependency-path: '**/go.sum'
      - name: Install dependencies
        run: go get ./...
      - name: Run test suite
        run: make test-ci > test_results.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: backend_test_results
          path: '**/test_results.json'
