name: Run frontend test suite

on:
  pull_request:
    paths:
      - '**.ts'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
        working-directory: ./frontend
      - run: npm run test
        working-directory: ./frontend
